version: '3.8'

services:
  ocpp-server:
    build:
      context: ../../
      dockerfile: apps/ocpp-server/Dockerfile
    ports:
      - "9220:9220"
    environment:
      - OCPP_PORT=9220
      - MONGODB_URI=mongodb+srv://cloud:eFtnSh3VyUxGMZbO@cluster0.y0hnvsx.mongodb.net/ev_platform
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
    depends_on:
      - redis
      - rabbitmq
    networks:
      - ev-network

  api-gateway:
    build:
      context: ../../
      dockerfile: apps/api-gateway/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - GATEWAY_PORT=3000
      - REDIS_URL=redis://redis:6379
      - ADMIN_API_URL=http://admin-api:3002
      - USER_API_URL=http://user-api:3001
    depends_on:
      - ocpp-server
      - user-api
      - admin-api
      - redis
    networks:
      - ev-network

  user-api:
    build:
      context: ../../
      dockerfile: apps/user-api/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - USER_API_PORT=3001
      - JWT_SECRET=ev-platform-secret-key
      - MONGODB_URI=mongodb+srv://cloud:eFtnSh3VyUxGMZbO@cluster0.y0hnvsx.mongodb.net/ev_platform
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
    depends_on:
      - redis
      - rabbitmq
    networks:
      - ev-network

  admin-api:
    build:
      context: ../../
      dockerfile: apps/admin-api/Dockerfile
    ports:
      - "3002:3002"
    environment:
      - ADMIN_API_PORT=3002
      - MONGODB_URI=mongodb+srv://cloud:eFtnSh3VyUxGMZbO@cluster0.y0hnvsx.mongodb.net/ev_platform
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
    depends_on:
      - redis
      - rabbitmq
    networks:
      - ev-network

  # admin-web:
  #   build:
  #     context: ../../frontend/admin-web
  #     dockerfile: Dockerfile
  #     args:
  #       - VITE_APP_API_URL=http://localhost:3000
  #   ports:
  #     - "3004:80"
  #   depends_on:
  #     - api-gateway
  #   networks:
  #     - ev-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - ev-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - ev-network

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - ev-network

  grafana:
    image: grafana/grafana
    ports:
      - "3003:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_SECURITY_COOKIE_SAMESITE=none
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    depends_on:
      - prometheus
    networks:
      - ev-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # Web UI
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - ev-network

networks:
  ev-network:
    driver: bridge
